
import { Product, Category, User, Order } from "./types";

// Category data
export const categories: Category[] = [
  {
    id: 1,
    name: "Fresh Fruits",
    image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?q=80&w=1170&auto=format&fit=crop",
    productCount: 10,
  },
  {
    id: 2,
    name: "Fresh Vegetables",
    image: "https://images.unsplash.com/photo-1597362925123-77861d3fbac7?q=80&w=1170&auto=format&fit=crop",
    productCount: 10,
  },
  {
    id: 3,
    name: "Dry Fruits",
    image: "https://images.unsplash.com/photo-1767877609689-beff32b9c0ac?q=80&w=2069&auto=format&fit=crop",
    productCount: 10,
  },
  {
    id: 4,
    name: "Snacks",
    image: "https://images.unsplash.com/photo-1614735241165-6756e1df61ab?q=80&w=1632&auto=format&fit=crop",
    productCount: 10,
  },
  {
    id: 5,
    name: "Fresh Juices",
    image: "https://images.unsplash.com/photo-1657101455328-6821c90b0ad3?q=80&w=881&auto=format&fit=crop",
    productCount: 5,
  },
  {
    id: 6,
    name: "Organic Products",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=684&auto=format&fit=crop",
    productCount: 4,
  },
];

// Product data
export const products: Product[] = [
  // Fresh Fruits Category
  {
    id: 1,
    name: "Organic Apples",
    description: "Fresh and juicy organic apples picked at the peak of ripeness. Rich in antioxidants and vitamins, these apples make a perfect healthy snack or baking ingredient.",
    price: 3.99,
    discountedPrice: 2.99,
    category: "Fresh Fruits",
    tags: ["organic", "fruit", "apple"],
    stock: 50,
    images: [
      "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?q=80&w=1170&auto=format&fit=crop",
    ],
    rating: 4.8,
    reviews: [
      {
        id: 1,
        userId: 2,
        userName: "Emma Johnson",
        rating: 5,
        comment: "These apples are so fresh and delicious! Will buy again.",
        date: "2024-03-15",
      },
    ],
    featured: true,
  },
  {
    id: 2,
    name: "Sweet Bananas",
    description: "Naturally sweet and energy-packed bananas. Perfect for smoothies, baking, or eating fresh as a quick and nutritious snack.",
    price: 2.49,
    category: "Fresh Fruits",
    tags: ["fruit", "banana", "smoothie"],
    stock: 80,
    images: [
      "https://images.unsplash.com/photo-1603833665858-e61d17a86224?q=80&w=1169&auto=format&fit=crop",
    ],
    rating: 4.5,
    reviews: [],
    featured: true,
  },
  {
    id: 3,
    name: "Juicy Oranges",
    description: "Vitamin C-rich oranges with bright, tangy flavor. Perfect for juicing or enjoying as a refreshing snack.",
    price: 4.99,
    discountedPrice: 3.99,
    category: "Fresh Fruits",
    tags: ["fruit", "orange", "vitamin c"],
    stock: 40,
    images: [
      "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?q=80&w=1935&auto=format&fit=crop",
    ],
    rating: 4.7,
    reviews: [],
    featured: false,
  },
  {
    id: 4,
    name: "Strawberries",
    description: "Plump, sweet strawberries grown in our local farms. Perfect for desserts, jams, or eating fresh.",
    price: 5.99,
    category: "Fresh Fruits",
    tags: ["fruit", "strawberry", "berry"],
    stock: 30,
    images: [
      "https://images.unsplash.com/photo-1587393855524-087f83d95bc9?q=80&w=760&auto=format&fit=crop",
    ],
    rating: 4.9,
    reviews: [],
    featured: true,
  },
  {
    id: 5,
    name: "Mango",
    description: "Sweet and aromatic mangoes. Rich in vitamins and perfect for smoothies, desserts, or enjoying fresh.",
    price: 6.99,
    discountedPrice: 5.99,
    category: "Fresh Fruits",
    tags: ["fruit", "mango", "tropical"],
    stock: 25,
    images: [
      "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?q=80&w=1935&auto=format&fit=crop",
    ],
    rating: 4.8,
    reviews: [],
    featured: false,
  },
  {
    id: 6,
    name: "Blueberries",
    description: "Antioxidant-rich blueberries packed with flavor. Great for baking, smoothies, or as a healthy snack.",
    price: 7.99,
    category: "Fresh Fruits",
    tags: ["fruit", "blueberry", "antioxidant"],
    stock: 20,
    images: [
      "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?q=80&w=1769&auto=format&fit=crop",
    ],
    rating: 4.6,
    reviews: [],
    featured: false,
  },
  {
    id: 7,
    name: "Watermelon",
    description: "Refreshing and hydrating watermelon. Perfect for hot summer days and gatherings.",
    price: 8.99,
    discountedPrice: 7.49,
    category: "Fresh Fruits",
    tags: ["fruit", "watermelon", "summer"],
    stock: 15,
    images: [
      "https://images.unsplash.com/photo-1708982553355-794739c6693e?w=700&auto=format&fit=crop",
    ],
    rating: 4.7,
    reviews: [],
    featured: true,
  },
  {
    id: 8,
    name: "Grapes",
    description: "Sweet and juicy grapes. Perfect for snacking, adding to fruit salads, or making juice.",
    price: 5.49,
    category: "Fresh Fruits",
    tags: ["fruit", "grape"],
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1596363505729-4190a9506133?q=80&w=1935&auto=format&fit=crop",
    ],
    rating: 4.5,
    reviews: [],
    featured: false,
  },
  {
    id: 9,
    name: "Pineapple",
    description: "Sweet and tangy pineapple. Rich in vitamin C and perfect for tropical desserts and smoothies.",
    price: 5.99,
    discountedPrice: 4.99,
    category: "Fresh Fruits",
    tags: ["fruit", "pineapple", "tropical"],
    stock: 20,
    images: [
      "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?q=80&w=1887&auto=format&fit=crop",
    ],
    rating: 4.6,
    reviews: [],
    featured: false,
  },
  {
    id: 10,
    name: "Kiwi Fruit",
    description: "Nutrient-dense kiwi fruit with a unique sweet-tart flavor. High in vitamin C and dietary fiber.",
    price: 4.49,
    category: "Fresh Fruits",
    tags: ["fruit", "kiwi", "vitamin c"],
    stock: 30,
    images: [
      "https://plus.unsplash.com/premium_photo-1674382739482-5d36b98d653a?w=700&auto=format&fit=crop",
    ],
    rating: 4.4,
    reviews: [],
    featured: false,
  },

  // Fresh Vegetables Category
  {
    id: 11,
    name: "Fresh Spinach",
    description: "Nutrient-rich spinach leaves, perfect for salads, smoothies, or cooking. High in iron and vitamins.",
    price: 3.49,
    discountedPrice: 2.99,
    category: "Fresh Vegetables",
    tags: ["vegetable", "spinach", "leafy green"],
    stock: 40,
    images: [
      "https://images.unsplash.com/photo-1576045057995-568f588f82fb?q=80&w=1780&auto=format&fit=crop",
    ],
    rating: 4.7,
    reviews: [],
    featured: true,
  },
  {
    id: 12,
    name: "Tomatoes",
    description: "Vine-ripened tomatoes with rich flavor. Perfect for salads, sauces, or sandwiches.",
    price: 3.99,
    category: "Fresh Vegetables",
    tags: ["vegetable", "tomato"],
    stock: 50,
    images: [
      "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?q=80&w=1769&auto=format&fit=crop",
    ],
    rating: 4.5,
    reviews: [],
    featured: false,
  },
  {
    id: 13,
    name: "Bell Peppers",
    description: "Colorful bell peppers, sweet and crunchy. Great for stir-fries, salads, or stuffed dishes.",
    price: 4.49,
    discountedPrice: 3.99,
    category: "Fresh Vegetables",
    tags: ["vegetable", "pepper", "bell pepper"],
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1592548868664-f8b4e4b1cfb7?w=700&auto=format&fit=crop",
    ],
    rating: 4.6,
    reviews: [],
    featured: true,
  },
  {
    id: 14,
    name: "Carrots",
    description: "Crunchy, sweet carrots. Rich in beta-carotene and perfect for snacking, cooking, or juicing.",
    price: 2.99,
    category: "Fresh Vegetables",
    tags: ["vegetable", "carrot", "root"],
    stock: 60,
    images: [
      "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=700&auto=format&fit=crop",
    ],
    rating: 4.8,
    reviews: [],
    featured: false,
  },
  {
    id: 15,
    name: "Broccoli",
    description: "Nutritious broccoli florets. High in vitamins and minerals, perfect for steaming, roasting, or stir-fries.",
    price: 3.79,
    discountedPrice: 3.29,
    category: "Fresh Vegetables",
    tags: ["vegetable", "broccoli", "cruciferous"],
    stock: 30,
    images: [
      "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?q=80&w=1802&auto=format&fit=crop",
    ],
    rating: 4.5,
    reviews: [],
    featured: false,
  },
  {
    id: 16,
    name: "Cucumber",
    description: "Crisp and refreshing cucumbers. Low in calories and perfect for salads or light snacks.",
    price: 2.49,
    category: "Fresh Vegetables",
    tags: ["vegetable", "cucumber"],
    stock: 45,
    images: [
      "https://images.unsplash.com/photo-1604977042946-1eecc30f269e?q=80&w=1887&auto=format&fit=crop",
    ],
    rating: 4.4,
    reviews: [],
    featured: false,
  },
  {
    id: 17,
    name: "Onions",
    description: "Versatile onions, perfect for adding flavor to almost any savory dish.",
    price: 2.29,
    discountedPrice: 1.99,
    category: "Fresh Vegetables",
    tags: ["vegetable", "onion"],
    stock: 70,
    images: [
      "https://images.unsplash.com/photo-1620574387735-3624d75b2dbc?w=700&auto=format&fit=crop",
    ],
    rating: 4.3,
    reviews: [],
    featured: false,
  },
  {
    id: 18,
    name: "Potatoes",
    description: "Versatile potatoes, perfect for baking, mashing, or making fries. A kitchen staple.",
    price: 3.49,
    category: "Fresh Vegetables",
    tags: ["vegetable", "potato", "root"],
    stock: 80,
    images: [
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=1770&auto=format&fit=crop",
    ],
    rating: 4.7,
    reviews: [],
    featured: true,
  },
  {
    id: 19,
    name: "Lettuce",
    description: "Crisp and fresh lettuce. Perfect for salads, sandwiches, or wraps.",
    price: 2.99,
    discountedPrice: 2.49,
    category: "Fresh Vegetables",
    tags: ["vegetable", "lettuce", "leafy green"],
    stock: 40,
    images: [
      "https://images.unsplash.com/photo-1640958904159-51ae08bd3412?w=700&auto=format&fit=crop",
    ],
    rating: 4.2,
    reviews: [],
    featured: false,
  },
  {
    id: 20,
    name: "Zucchini",
    description: "Versatile zucchini, perfect for grilling, baking, or adding to pasta dishes.",
    price: 2.79,
    category: "Fresh Vegetables",
    tags: ["vegetable", "zucchini", "squash"],
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1589621316382-008455b857cd?q=80&w=1770&auto=format&fit=crop",
    ],
    rating: 4.4,
    reviews: [],
    featured: false,
  },

  // Dry Fruits Category
  {
    id: 21,
    name: "Almonds",
    description: "Nutrient-dense almonds, rich in healthy fats, protein, and vitamins. Perfect for snacking or adding to recipes.",
    price: 11.99,
    discountedPrice: 9.99,
    category: "Dry Fruits",
    tags: ["dry fruit", "almond", "nut"],
    stock: 50,
    images: [
      "https://plus.unsplash.com/premium_photo-1675237626334-5cf9d9d8b30c?w=700&auto=format&fit=crop",
    ],
    rating: 4.9,
    reviews: [],
    featured: true,
  },
  {
    id: 22,
    name: "Walnuts",
    description: "Crunchy walnuts packed with omega-3 fatty acids. Great for baking, salads, or eating plain.",
    price: 13.99,
    category: "Dry Fruits",
    tags: ["dry fruit", "walnut", "nut"],
    stock: 40,
    images: [
      "https://images.unsplash.com/photo-1524593000379-d4729b2c4f99?w=700&auto=format&fit=crop",
    ],
    rating: 4.7,
    reviews: [],
    featured: false,
  },
  {
    id: 23,
    name: "Raisins",
    description: "Sweet, dried raisins. Perfect for baking, cereal, or as a healthy snack.",
    price: 6.99,
    discountedPrice: 5.99,
    category: "Dry Fruits",
    tags: ["dry fruit", "raisin", "grape"],
    stock: 60,
    images: [
      "https://images.unsplash.com/photo-1642102903918-b97c37955bbf?w=700&auto=format&fit=crop",
    ],
    rating: 4.5,
    reviews: [],
    featured: false,
  },
  {
    id: 24,
    name: "Dates",
    description: "Sweet and chewy dates, a natural energy booster rich in nutrients and fiber.",
    price: 8.99,
    category: "Dry Fruits",
    tags: ["dry fruit", "date"],
    stock: 45,
    images: [
      "https://plus.unsplash.com/premium_photo-1676208753932-6e8bc83a0b0d?w=700&auto=format&fit=crop",
    ],
    rating: 4.8,
    reviews: [],
    featured: true,
  },
  {
    id: 25,
    name: "Cashews",
    description: "Creamy, delicious cashews. Rich in heart-healthy fats and perfect for snacking or cooking.",
    price: 12.99,
    discountedPrice: 11.49,
    category: "Dry Fruits",
    tags: ["dry fruit", "cashew", "nut"],
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1726771517475-e7acdd34cd8a?q=80&w=870&auto=format&fit=crop",
    ],
    rating: 4.6,
    reviews: [],
    featured: false,
  },
  {
    id: 26,
    name: "Pistachios",
    description: "Flavorful pistachios, rich in antioxidants and heart-healthy nutrients.",
    price: 14.99,
    category: "Dry Fruits",
    tags: ["dry fruit", "pistachio", "nut"],
    stock: 30,
    images: [
      "https://plus.unsplash.com/premium_photo-1726072356920-a39aaa49ce89?w=700&auto=format&fit=crop",
    ],
    rating: 4.9,
    reviews: [],
    featured: true,
  },
  {
    id: 27,
    name: "Dried Apricots",
    description: "Sweet and tangy dried apricots, rich in fiber and vitamins. Perfect for snacking or baking.",
    price: 9.99,
    discountedPrice: 8.49,
    category: "Dry Fruits",
    tags: ["dry fruit", "apricot", "dried"],
    stock: 40,
    images: [
      "https://plus.unsplash.com/premium_photo-1669205340693-755739ea443d?w=700&auto=format&fit=crop",
    ],
    rating: 4.5,
    reviews: [],
    featured: false,
  },
  {
    id: 28,
    name: "Dried Cranberries",
    description: "Tart and sweet dried cranberries. Perfect for salads, baking, or snacking.",
    price: 7.99,
    category: "Dry Fruits",
    tags: ["dry fruit", "cranberry", "dried"],
    stock: 45,
    images: [
      "https://images.unsplash.com/photo-1772986832186-89f2092a7e1f?w=700&auto=format&fit=crop",
    ],
    rating: 4.4,
    reviews: [],
    featured: false,
  },
  {
    id: 29,
    name: "Fig",
    description: "Sweet, chewy dried figs. Rich in fiber and nutrients, perfect for snacks or desserts.",
    price: 10.99,
    discountedPrice: 9.99,
    category: "Dry Fruits",
    tags: ["dry fruit", "fig", "dried"],
    stock: 25,
    images: [
      "https://images.unsplash.com/photo-1633932850276-4382027c868a?w=700&auto=format&fit=crop",
    ],
    rating: 4.7,
    reviews: [],
    featured: false,
  },
  {
    id: 30,
    name: "Mixed Nuts",
    description: "Premium assortment of mixed nuts. A perfect blend of flavors and nutrients.",
    price: 15.99,
    category: "Dry Fruits",
    tags: ["dry fruit", "mixed nuts", "assorted"],
    stock: 30,
    images: [
      "https://plus.unsplash.com/premium_photo-1668677227454-213252229b73?w=700&auto=format&fit=crop",
    ],
    rating: 4.8,
    reviews: [],
    featured: true,
  },

  // Snacks Category
  {
    id: 31,
    name: "Veggie Chips",
    description: "Crunchy veggie chips made from real vegetables. A healthier alternative to regular chips.",
    price: 4.99,
    discountedPrice: 3.99,
    category: "Snacks",
    tags: ["snack", "chips", "vegetable"],
    stock: 40,
    images: [
      "https://images.unsplash.com/photo-1739065882816-8fdfac4516e2?w=700&auto=format&fit=crop",
    ],
    rating: 4.6,
    reviews: [],
    featured: true,
  },
  {
    id: 32,
    name: "Fruit Trail Mix",
    description: "Energizing trail mix with dried fruits and nuts. Perfect for on-the-go snacking.",
    price: 7.99,
    category: "Snacks",
    tags: ["snack", "trail mix", "dried fruit"],
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1606320381205-13de1f55521d?w=700&auto=format&fit=crop",
    ],
    rating: 4.7,
    reviews: [],
    featured: false,
  },
  {
    id: 33,
    name: "Popcorn",
    description: "Light and crispy popcorn. A whole grain snack that's perfect for movie nights.",
    price: 3.99,
    discountedPrice: 2.99,
    category: "Snacks",
    tags: ["snack", "popcorn", "whole grain"],
    stock: 50,
    images: [
      "https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?w=700&auto=format&fit=crop",
    ],
    rating: 4.5,
    reviews: [],
    featured: true,
  },
  {
    id: 34,
    name: "Granola Bars",
    description: "Nutritious granola bars packed with oats, honey, and dried fruits. Perfect for a quick energy boost.",
    price: 6.99,
    category: "Snacks",
    tags: ["snack", "granola", "bar"],
    stock: 45,
    images: [
      "https://images.unsplash.com/photo-1621057621391-7ed446a24b41?w=700&auto=format&fit=crop",
    ],
    rating: 4.6,
    reviews: [],
    featured: false,
  },
  {
    id: 35,
    name: "Rice Cakes",
    description: "Light and crunchy rice cakes. A low-calorie snack option perfect for topping with your favorites.",
    price: 3.49,
    discountedPrice: 2.99,
    category: "Snacks",
    tags: ["snack", "rice cake", "low calorie"],
    stock: 55,
    images: [
      "https://plus.unsplash.com/premium_photo-1699519510499-41b626d8522e?w=700&auto=format&fit=crop",
    ],
    rating: 4.2,
    reviews: [],
    featured: false,
  },
  {
    id: 36,
    name: "Hummus Dip",
    description: "Creamy hummus made from chickpeas and tahini. Perfect for dipping vegetables or pita bread.",
    price: 5.49,
    category: "Snacks",
    tags: ["snack", "hummus", "dip"],
    stock: 30,
    images: [
      "https://images.unsplash.com/photo-1697126248437-db26a30024c5?w=700&auto=format&fit=crop",
    ],
    rating: 4.8,
    reviews: [],
    featured: true,
  },
  {
    id: 37,
    name: "Yogurt-Covered Raisins",
    description: "Sweet raisins coated in creamy yogurt. A delicious treat that balances sweetness with nutrition.",
    price: 6.49,
    discountedPrice: 5.99,
    category: "Snacks",
    tags: ["snack", "yogurt", "raisin"],
    stock: 25,
    images: [
      "https://images.unsplash.com/photo-1597612949739-30735becd27b?w=700&auto=format&fit=crop",
    ],
    rating: 4.5,
    reviews: [],
    featured: false,
  },
  {
    id: 38,
    name: "Roasted Chickpeas",
    description: "Crunchy roasted chickpeas seasoned with herbs and spices. A protein-rich snacking option.",
    price: 4.99,
    category: "Snacks",
    tags: ["snack", "chickpea", "protein"],
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1760942852135-e98d57fe0ba2?w=700&auto=format&fit=crop",
    ],
    rating: 4.4,
    reviews: [],
    featured: false,
  },
  {
    id: 39,
    name: "Kale Chips",
    description: "Crispy baked kale chips. A nutrient-dense alternative to traditional chips.",
    price: 5.99,
    discountedPrice: 4.99,
    category: "Snacks",
    tags: ["snack", "kale", "chips"],
    stock: 30,
    images: [
      "https://plus.unsplash.com/premium_photo-1703254870878-287d804cb3cf?w=700&auto=format&fit=crop",
    ],
    rating: 4.3,
    reviews: [],
    featured: false,
  },
  {
    id: 40,
    name: "Energy Balls",
    description: "No-bake energy balls made with oats, nuts, and dried fruits. Perfect for a quick energy boost.",
    price: 8.99,
    category: "Snacks",
    tags: ["snack", "energy", "protein"],
    stock: 25,
    images: [
      "https://images.unsplash.com/photo-1716392916280-e17fb5a2c191?w=700&auto=format&fit=crop",
    ],
    rating: 4.7,
    reviews: [],
    featured: true,
  },

  // Oraganic Products Category
  {
    id: 41,
    name: "Organic Honey",
    description: "Pure, unprocessed honey sourced from organic farms. Rich in antioxidants and natural sweetness.",
    price: 8.99,
    category: "Organic Products",
    tags: ["honey", "organic", "natural", "sweetener"],
    stock: 20,
    images: [
      "https://images.unsplash.com/photo-1587049352851-8d4e89133924?q=80&w=600&auto=format&fit=crop",
    ],
    rating: 4.9,
    reviews: [],
    featured: true,
  },
  {
    id: 42,
    name: "Rosemary Olive",
    description: "Pure, unprocessed olive oil infused with the aroma of fresh rosemary. Perfect for drizzling over salads or roasting vegetables.",
    price: 6.99,
    category: "Organic Products",
    tags: ["Rosemary", "organic", "natural", "leaves"],
    stock: 20,

    images: [
      "https://images.unsplash.com/photo-1650964336695-448cc983e700?q=80&w=880&auto=format&fit=crop",
    ],
    rating: 4.8,
    reviews: [],
    featured: true,
  },
  {
    id: 43,
    name: "Body Oil",
    description: "Moisturizing body oil infused with natural ingredients. Perfect for hydrating and nourishing the skin.",
    price: 8.99,
    category: "Organic Products",
    tags: ["body", "oil", "organic", "natural"],
    stock: 20,

    images: [
      "https://images.unsplash.com/photo-1532413992378-f169ac26fff0?q=80&w=880&auto=format&fit=crop",
    ],
    rating: 4.9,
    reviews: [],
    featured: true,
  },
  {
    id: 44,
    name: "Body Soap",
    description: "Gentle cleansing body soap infused with natural ingredients. Perfect for daily use and sensitive skin.",
    price: 5.99,
    category: "Organic Products",
    tags: ["body", "soap", "organic", "natural"],
    stock: 20,

    images: [
      "https://images.unsplash.com/photo-1618111415604-afe870dbb72a?q=80&w=687&auto=format&fit=crop",
    ],
    rating: 4.8,
    reviews: [],
    featured: true,
  },

  // Fresh Juices Category
  {
    id: 45,
    name: "Orange Juice",
    description: "Freshly squeezed orange juice with no added sugar or preservatives. Rich in vitamin C and perfect for breakfast.",
    price: 5.99,
    category: "Fresh Juices",
    tags: ["juice", "orange", "fresh", "breakfast", "vitamin"],
    stock: 15,
    images: [
      "https://plus.unsplash.com/premium_photo-1675667390417-d9d23160f4a6?q=80&w=687&auto=format&fit=crop",
    ],
    rating: 4.8,
    reviews: [],
    featured: true,
  },
  {
    id: 46,
    name: "Strawberry juice",
    description: "Freshly squeezed strawberry juice with no added sugar or preservatives. Sweet and delicious, perfect for a refreshing drink.",
    price: 6.99,
    category: "Fresh Juices",
    tags: ["juice", "strawberry", "fresh", "refreshing"],
    stock: 20,
    images: [
      "https://plus.unsplash.com/premium_photo-1675667756988-e73d68e5abf1?q=80&w=687&auto=format&fit=crop",
    ],
    rating: 4.9,
    reviews: [],
    featured: true,
  },
  {
    id: 47,
    name: "Mango Juice",
    description: "Freshly squeezed mango juice with no added sugar or preservatives. Sweet and tropical, perfect for a refreshing drink.",
    price: 5.99,
    category: "Fresh Juices",
    tags: ["juice", "mango", "fresh", "tropical"],
    stock: 20,

    images: [
      "https://images.unsplash.com/photo-1697642452436-9c40773cbcbb?q=80&w=765&auto=format&fit=crop",
    ],
    rating: 4.7,
    reviews: [],
    featured: true,
  },
  {
    id: 48,
    name: "Watermelon Juice",
    description: "Freshly squeezed watermelon juice with no added sugar or preservatives. Refreshing and hydrating, perfect for hot days.",
    price: 5.99,
    category: "Fresh Juices",
    tags: ["juice", "watermelon", "fresh", "refreshing"],
    stock: 20,

    images: [
      "https://images.unsplash.com/photo-1634141572430-cc6c46de1cf6?q=80&w=687&auto=format&fit=crop",
    ],
    rating: 4.8,
    reviews: [],
    featured: true,
  },
  {
    id: 49,
    name: "Pomegranate Juice",
    description: "Freshly squeezed pomegranate juice with no added sugar or preservatives. Rich in antioxidants and perfect for a healthy drink.",
    price: 6.99,
    category: "Fresh Juices",
    tags: ["juice", "pomegranate", "fresh", "antioxidants"],
    stock: 20,

    images: [
      "https://images.unsplash.com/photo-1568909344668-6f14a07b56a0?q=80&w=735&auto=format&fit=crop",
    ],
    rating: 4.8,
    reviews: [],
    featured: true,
  },
];

// User data
export const users: User[] = [
  {
    id: 1,
    name: "Admin User",
    email: "admin@farmfresh.com",
    role: "admin",
    avatar: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?q=80&w=1780&auto=format&fit=crop",
    address: {
      street: "123 Admin Street",
      city: "Admin City",
      state: "California",
      zipCode: "90210",
      country: "USA",
    },
  },
  {
    id: 2,
    name: "Emma Johnson",
    email: "emma@example.com",
    role: "user",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=1888&auto=format&fit=crop",
    address: {
      street: "456 Customer Road",
      city: "Los Angeles",
      state: "California",
      zipCode: "90001",
      country: "USA",
    },
  },
  {
    id: 3,
    name: "Michael Smith",
    email: "michael@example.com",
    role: "user",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=1770&auto=format&fit=crop",
    address: {
      street: "789 Oak Street",
      city: "San Francisco",
      state: "California",
      zipCode: "94101",
      country: "USA",
    },
  },
];

// Sample Orders
export const orders: Order[] = [
  {
    id: 1,
    userId: 2,
    items: [
      {
        productId: 1,
        quantity: 2,
        name: "Organic Apples",
        price: 2.99,
        image: "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?q=80&w=1170&auto=format&fit=crop",
      },
      {
        productId: 11,
        quantity: 1,
        name: "Fresh Spinach",
        price: 2.99,
        image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?q=80&w=1780&auto=format&fit=crop",
      },
    ],
    totalAmount: 8.97,
    status: "delivered",
    paymentMethod: "card",
    createdAt: "2023-12-15T12:30:45",
    updatedAt: "2023-12-16T15:20:10",
  },
  {
    id: 2,
    userId: 3,
    items: [
      {
        productId: 21,
        quantity: 1,
        name: "Almonds",
        price: 9.99,
        image: "https://images.unsplash.com/photo-1574708094872-12b9d9c92399?q=80&w=1769&auto=format&fit=crop",
      },
    ],
    totalAmount: 9.99,
    status: "processing",
    paymentMethod: "cod",
    createdAt: "2024-01-05T09:15:30",
    updatedAt: "2024-01-05T09:15:30",
  },
];

export const faqs = [
  {
    question: "How does Farm Fresh ensure the quality of its products?",
    answer: "We work directly with local farmers who follow sustainable farming practices. All produce is carefully inspected for freshness and quality before being delivered to your doorstep. We also prioritize seasonal items to ensure you get the best flavor and nutritional value."
  },
  {
    question: "What areas do you deliver to?",
    answer: "We currently deliver to most areas within California. Enter your zip code during checkout to confirm if we deliver to your location. We're continuously expanding our delivery network to reach more communities."
  },
  {
    question: "How is my order packaged?",
    answer: "We use eco-friendly packaging materials to ensure your products arrive fresh and undamaged. Fragile items are carefully wrapped, and temperature-sensitive products are packed with appropriate insulation when needed."
  },
  {
    question: "What is your return policy?",
    answer: "If you're not satisfied with the quality of any product, please contact our customer service within 24 hours of delivery. We'll either refund your money or replace the item in your next order, depending on your preference."
  },
  {
    question: "How do I track my order?",
    answer: "Once your order is confirmed and shipped, you'll receive a tracking link via email. You can also check the status of your delivery by logging into your account and viewing your order history."
  },
  {
    question: "Are your fruits and vegetables organic?",
    answer: "We offer both organic and conventionally grown produce. Organic items are clearly labeled as such on our website. All our farmers, whether organic or conventional, follow responsible growing practices."
  },
  {
    question: "What payment methods do you accept?",
    answer: "We accept all major credit cards, PayPal, and Apple Pay. For regular customers, we also offer the option of cash on delivery (COD)."
  },
  {
    question: "Can I modify or cancel my order after it's placed?",
    answer: "You can modify or cancel your order within 2 hours of placing it. After that, please contact our customer service team, and we'll do our best to accommodate your request if the order hasn't been processed yet."
  },
  {
    question: "Do you offer subscriptions or recurring orders?",
    answer: "Yes, we offer weekly and monthly subscription boxes that can be customized to your preferences. Subscribers enjoy additional benefits like free delivery and exclusive discounts."
  },
  {
    question: "How fresh are your products?",
    answer: "We harvest most of our produce within 24-48 hours of delivery to ensure maximum freshness. Our dry goods and packaged products are always well within their shelf life, and we regularly rotate our inventory."
  }
];
